### ISSUE TITLE
现在这个一键脚本用不了了吗？

### ISSUE THREAD

**Issue by ghost** [lidalao/ServerStatus#11]
换了三个机器都失败显示这个

Traceback (most recent call last):
  File "_sss.py", line 249, in <module>
    cmd()
  File "_sss.py", line 213, in cmd
    print('- - - \u6b22\u8fce\u4f7f\u7528\u6700\u7b80\u6d01\u7684\u63a2\u9488: Server Status - - -')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 6-15: ordinal not in range(256)

**Comment by ota1-letzgame** [comment]
#4

**Comment by lidalao** [comment]
#4
