### ISSUE TITLE
大佬bot报错，有详细的添加注释吗？？

### ISSUE THREAD

**Issue by sanwan2009** [lidalao/ServerStatus#2]
root@-host:~/sss# python3 ./bot.py
  File "./bot.py", line 73
    sscmd(NODE_STATUS_URL)_ == '__main__':
                          ^
SyntaxError: invalid syntax

**Comment by sanwan2009** [comment]
NODE_STATUS_URL = 'http://ss.tk:8081/json/stats.json'

offs = []
counterOff = {}
counterOn = {}

def _send(text):
    chat_id = os.getenv('TG_CHAT_ID')
    bot_token = os.environ.get('TG_BOT_TOKEN')
    url = f"https://api.telegram.org/bot{101477704:AAHcZyavW1BZnEFvSvecmiiaqnpJHP9wKTI}/sendMessage?parse_mode=HTML&disable_web_page_preview=true&chat_id=39995195" + chat_id + "&text=" + text

**Comment by lidalao** [comment]
怀疑你是把一些代码缩紧去掉了，对吗？

**Comment by sanwan2009** [comment]
对呀！正确的填写应该是在上面吗？可以给一个示范吗？谢谢

**Comment by sanwan2009** [comment]
NODE_STATUS_URL = 'http://sss.tk:8081/json/stats.json'

offs = []
counterOff = {}
counterOn = {}

def _send(text):
    chat_id = os.getenv('TG_CHAT_ID34888195')
    bot_token = os.environ.get('TG_BOT_TOKEN10000704:AAHcZyavW1BZnEFvSvecmiiaqnpJHP9wKTI')
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage?parse_mode=HTML&disable_web_page_preview=true&chat_id=" + chat_id + "&text=" + text

**Comment by lidalao** [comment]
chat_id = '34888195'
bot_token = '10000704:AAHcZyavW1BZnEFvSvecmiiaqnpJHP9wKTI'

--
这样就可以了

**Comment by sanwan2009** [comment]
好的，明白了谢谢

**Comment by sanwan2009** [comment]
好的，明白了谢谢
