### ISSUE TITLE
请问完成部署后如何修改bot token？

### ISSUE THREAD

**Issue by Nigel-NI** [lidalao/ServerStatus#7]
之前部署用的bot我想用在别的推送上，给serverstatus申请了一个新的bot，但是重新执行sss.sh并附带新参数后重新部署，还是推通过原来的bot推送，而不是通过新途径。尝试过重启主机，但是仍然不生效。请问如果想通过新api推送，有没有什么简便的方法呢？

**Comment by ota1-letzgame** [comment]
1. 更改bot.py文件，里面有发送内容。
2. 在sss文件夹下执行，
`docker-compose down && docker-compose build && docker-compose up -d
`

**Comment by lidalao** [comment]
更改bot.py文件后，在sss文件夹下执行，
`docker-compose down && docker-compose build && docker-compose up -d`
