### ISSUE TITLE
执行sss.sh报错

### ISSUE THREAD

**Issue by rayle2** [lidalao/ServerStatus#8]
Traceback (most recent call last):
  File "_sss.py", line 249, in <module>
    cmd()
  File "_sss.py", line 213, in cmd
    print('- - - \u6b22\u8fce\u4f7f\u7528\u6700\u7b80\u6d01\u7684\u63a2\u9488: Server Status - - -')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 6-15: ordinal not in range(256)

**Comment by lidalao** [comment]
bug同下，
#4
