### ISSUE TITLE
只有ipv6的机器貌似监控不了

### ISSUE THREAD

**Issue by xyzol** [lidalao/ServerStatus#9]
只有ipv6的机器貌似监控不了

**Comment by lidalao** [comment]
监控不了是指无法在web显示，还是没有上下线通知？

**Comment by xyzol** [comment]
> 监控不了是指无法在web显示，还是没有上下线通知？

感谢，我解决了，机器有问题，重装解决了，感谢。

另外请问TG机器人可以对接群吗，让上下线通知在群里显示。
